package com.xupt.ttms.mapper;

import com.xupt.ttms.pojo.Hall;
import com.xupt.ttms.pojo.HallExample;
import com.xupt.ttms.pojo.Seat;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int countByExample(HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int deleteByExample(HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int insert(Hall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int insertSelective(Hall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    List<Hall> selectByExample(HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    Hall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") Hall record, @Param("example") HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByExample(@Param("record") Hall record, @Param("example") HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByPrimaryKeySelective(Hall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByPrimaryKey(Hall record);

    int deleteById(@Param("ids") String ids);

    /**
     * 批量添加座位
     * @param seat
     * @return
     */
    int insertSeat(@Param("seat") List<Seat> seat);
}