package com.xupt.ttms.mapper;

import com.xupt.ttms.pojo.Insider;
import com.xupt.ttms.pojo.InsiderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InsiderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int countByExample(InsiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int deleteByExample(InsiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int insert(Insider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int insertSelective(Insider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    List<Insider> selectByExample(InsiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    Insider selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") Insider record, @Param("example") InsiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByExample(@Param("record") Insider record, @Param("example") InsiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByPrimaryKeySelective(Insider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insider
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByPrimaryKey(Insider record);
}