package com.xupt.ttms.mapper;

import com.xupt.ttms.pojo.MyLike;
import com.xupt.ttms.pojo.MyLikeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MyLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int countByExample(MyLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int deleteByExample(MyLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int insert(MyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int insertSelective(MyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    List<MyLike> selectByExample(MyLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    MyLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") MyLike record, @Param("example") MyLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByExample(@Param("record") MyLike record, @Param("example") MyLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByPrimaryKeySelective(MyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylike
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    int updateByPrimaryKey(MyLike record);
}