spring:
    mail:
        host: smtp.qq.com  # 邮件服务器主机名
        username:   # 邮箱账号
        password:   # 邮箱授权码
        port: 587  # 端口号
        protocol: smtp  # 发送协议，这里使用smtp协议
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        checkserveridentity: true
                        port: 465
                        trust: "*"
                        protocol: TLSv1.2
            test-connection: true
qq-mail:
    address: 
    nickname: 
    pwd: 
    port: 
    service: smtp.qq.com
