package com.xupt.ttms.pojo;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
@Component
public class HallExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public HallExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHNameIsNull() {
            addCriterion("h_name is null");
            return (Criteria) this;
        }

        public Criteria andHNameIsNotNull() {
            addCriterion("h_name is not null");
            return (Criteria) this;
        }

        public Criteria andHNameEqualTo(String value) {
            addCriterion("h_name =", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotEqualTo(String value) {
            addCriterion("h_name <>", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameGreaterThan(String value) {
            addCriterion("h_name >", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameGreaterThanOrEqualTo(String value) {
            addCriterion("h_name >=", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameLessThan(String value) {
            addCriterion("h_name <", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameLessThanOrEqualTo(String value) {
            addCriterion("h_name <=", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameLike(String value) {
            addCriterion("h_name like", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotLike(String value) {
            addCriterion("h_name not like", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameIn(List<String> values) {
            addCriterion("h_name in", values, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotIn(List<String> values) {
            addCriterion("h_name not in", values, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameBetween(String value1, String value2) {
            addCriterion("h_name between", value1, value2, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotBetween(String value1, String value2) {
            addCriterion("h_name not between", value1, value2, "hName");
            return (Criteria) this;
        }

        public Criteria andHRowIsNull() {
            addCriterion("h_row is null");
            return (Criteria) this;
        }

        public Criteria andHRowIsNotNull() {
            addCriterion("h_row is not null");
            return (Criteria) this;
        }

        public Criteria andHRowEqualTo(Integer value) {
            addCriterion("h_row =", value, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowNotEqualTo(Integer value) {
            addCriterion("h_row <>", value, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowGreaterThan(Integer value) {
            addCriterion("h_row >", value, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_row >=", value, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowLessThan(Integer value) {
            addCriterion("h_row <", value, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowLessThanOrEqualTo(Integer value) {
            addCriterion("h_row <=", value, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowIn(List<Integer> values) {
            addCriterion("h_row in", values, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowNotIn(List<Integer> values) {
            addCriterion("h_row not in", values, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowBetween(Integer value1, Integer value2) {
            addCriterion("h_row between", value1, value2, "hRow");
            return (Criteria) this;
        }

        public Criteria andHRowNotBetween(Integer value1, Integer value2) {
            addCriterion("h_row not between", value1, value2, "hRow");
            return (Criteria) this;
        }

        public Criteria andHColIsNull() {
            addCriterion("h_col is null");
            return (Criteria) this;
        }

        public Criteria andHColIsNotNull() {
            addCriterion("h_col is not null");
            return (Criteria) this;
        }

        public Criteria andHColEqualTo(Integer value) {
            addCriterion("h_col =", value, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColNotEqualTo(Integer value) {
            addCriterion("h_col <>", value, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColGreaterThan(Integer value) {
            addCriterion("h_col >", value, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_col >=", value, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColLessThan(Integer value) {
            addCriterion("h_col <", value, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColLessThanOrEqualTo(Integer value) {
            addCriterion("h_col <=", value, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColIn(List<Integer> values) {
            addCriterion("h_col in", values, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColNotIn(List<Integer> values) {
            addCriterion("h_col not in", values, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColBetween(Integer value1, Integer value2) {
            addCriterion("h_col between", value1, value2, "hCol");
            return (Criteria) this;
        }

        public Criteria andHColNotBetween(Integer value1, Integer value2) {
            addCriterion("h_col not between", value1, value2, "hCol");
            return (Criteria) this;
        }

        public Criteria andHDescIsNull() {
            addCriterion("h_desc is null");
            return (Criteria) this;
        }

        public Criteria andHDescIsNotNull() {
            addCriterion("h_desc is not null");
            return (Criteria) this;
        }

        public Criteria andHDescEqualTo(String value) {
            addCriterion("h_desc =", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescNotEqualTo(String value) {
            addCriterion("h_desc <>", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescGreaterThan(String value) {
            addCriterion("h_desc >", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescGreaterThanOrEqualTo(String value) {
            addCriterion("h_desc >=", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescLessThan(String value) {
            addCriterion("h_desc <", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescLessThanOrEqualTo(String value) {
            addCriterion("h_desc <=", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescLike(String value) {
            addCriterion("h_desc like", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescNotLike(String value) {
            addCriterion("h_desc not like", value, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescIn(List<String> values) {
            addCriterion("h_desc in", values, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescNotIn(List<String> values) {
            addCriterion("h_desc not in", values, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescBetween(String value1, String value2) {
            addCriterion("h_desc between", value1, value2, "hDesc");
            return (Criteria) this;
        }

        public Criteria andHDescNotBetween(String value1, String value2) {
            addCriterion("h_desc not between", value1, value2, "hDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hall
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 06 13:45:59 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hall
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}