package com.xupt.ttms.pojo;

import org.springframework.stereotype.Component;

@Component
public class Insider {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insider.id
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insider.username
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insider.password
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insider.job
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insider.phone
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private String phone;

    public Insider(String password) {
        this.password = password;
    }

    public Insider() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insider.id
     *
     * @return the value of insider.id
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insider.id
     *
     * @param id the value for insider.id
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insider.username
     *
     * @return the value of insider.username
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insider.username
     *
     * @param username the value for insider.username
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insider.password
     *
     * @return the value of insider.password
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insider.password
     *
     * @param password the value for insider.password
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insider.job
     *
     * @return the value of insider.job
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insider.job
     *
     * @param job the value for insider.job
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insider.phone
     *
     * @return the value of insider.phone
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insider.phone
     *
     * @param phone the value for insider.phone
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}