package com.xupt.ttms.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.stereotype.Component;
@Component
public class Movie {
    public Movie() {
    }

    public Movie(Integer id, String mName, String mType, Integer mLength, Double mPrice, String mDate, String mDirector, String mActor, Double mBoxOffice, Double mScore, String mIntroduction, String mImage, String status) {
        this.id = id;
        this.mName = mName;
        this.mType = mType;
        this.mLength = mLength;
        this.mPrice = mPrice;
        this.mDate = mDate;
        this.mDirector = mDirector;
        this.mActor = mActor;
        this.mBoxOffice = mBoxOffice;
        this.mScore = mScore;
        this.mIntroduction = mIntroduction;
        this.mImage = mImage;
        this.status = status;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.id
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_name
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_type
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private String mType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_length
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private Integer mLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_price
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private Double mPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_date
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING ,pattern = "yyyy-MM-dd",timezone ="GMT+8")
    private String mDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_director
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private String mDirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_actor
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private String mActor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_box_office
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private Double mBoxOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_score
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private Double mScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_introduction
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private String mIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_image
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private String mImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.status
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    private String status;

    public Movie(String mName, String mType, Integer mLength, Double mPrice, String mDate, String mDirector, String mActor, Double mBoxOffice, Double mScore, String mIntroduction, String mImage, String status) {
        this.mName = mName;
        this.mType = mType;
        this.mLength = mLength;
        this.mPrice = mPrice;
        this.mDate = mDate;
        this.mDirector = mDirector;
        this.mActor = mActor;
        this.mBoxOffice = mBoxOffice;
        this.mScore = mScore;
        this.mIntroduction = mIntroduction;
        this.mImage = mImage;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.id
     *
     * @return the value of movie.id
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.id
     *
     * @param id the value for movie.id
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_name
     *
     * @return the value of movie.m_name
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_name
     *
     * @param mName the value for movie.m_name
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_type
     *
     * @return the value of movie.m_type
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_type
     *
     * @param mType the value for movie.m_type
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmType(String mType) {
        this.mType = mType == null ? null : mType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_length
     *
     * @return the value of movie.m_length
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public Integer getmLength() {
        return mLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_length
     *
     * @param mLength the value for movie.m_length
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmLength(Integer mLength) {
        this.mLength = mLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_price
     *
     * @return the value of movie.m_price
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public Double getmPrice() {
        return mPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_price
     *
     * @param mPrice the value for movie.m_price
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmPrice(Double mPrice) {
        this.mPrice = mPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_date
     *
     * @return the value of movie.m_date
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getmDate() {
        return mDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_date
     *
     * @param mDate the value for movie.m_date
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmDate(String mDate) {
        this.mDate = mDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_director
     *
     * @return the value of movie.m_director
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getmDirector() {
        return mDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_director
     *
     * @param mDirector the value for movie.m_director
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmDirector(String mDirector) {
        this.mDirector = mDirector == null ? null : mDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_actor
     *
     * @return the value of movie.m_actor
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getmActor() {
        return mActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_actor
     *
     * @param mActor the value for movie.m_actor
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmActor(String mActor) {
        this.mActor = mActor == null ? null : mActor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_box_office
     *
     * @return the value of movie.m_box_office
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public Double getmBoxOffice() {
        return mBoxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_box_office
     *
     * @param mBoxOffice the value for movie.m_box_office
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmBoxOffice(Double mBoxOffice) {
        this.mBoxOffice = mBoxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_score
     *
     * @return the value of movie.m_score
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public Double getmScore() {
        return mScore;
    }

    @Override
    public String toString() {
        return "Movie{" +
                "id=" + id +
                ", mName='" + mName + '\'' +
                ", mType='" + mType + '\'' +
                ", mLength=" + mLength +
                ", mPrice=" + mPrice +
                ", mDate='" + mDate + '\'' +
                ", mDirector='" + mDirector + '\'' +
                ", mActor='" + mActor + '\'' +
                ", mBoxOffice=" + mBoxOffice +
                ", mScore=" + mScore +
                ", mIntroduction='" + mIntroduction + '\'' +
                ", mImage='" + mImage + '\'' +
                ", status='" + status + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_score
     *
     * @param mScore the value for movie.m_score
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmScore(Double mScore) {
        this.mScore = mScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_introduction
     *
     * @return the value of movie.m_introduction
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getmIntroduction() {
        return mIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_introduction
     *
     * @param mIntroduction the value for movie.m_introduction
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmIntroduction(String mIntroduction) {
        this.mIntroduction = mIntroduction == null ? null : mIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_image
     *
     * @return the value of movie.m_image
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getmImage() {
        return mImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_image
     *
     * @param mImage the value for movie.m_image
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setmImage(String mImage) {
        this.mImage = mImage == null ? null : mImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.status
     *
     * @return the value of movie.status
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.status
     *
     * @param status the value for movie.status
     *
     * @mbggenerated Wed Jul 06 15:34:23 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

}