package com.xupt.ttms.pojo;

import org.springframework.stereotype.Component;

@Component
public class MyLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylike.id
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylike.m_name
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylike.username
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylike.id
     *
     * @return the value of mylike.id
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylike.id
     *
     * @param id the value for mylike.id
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylike.m_name
     *
     * @return the value of mylike.m_name
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylike.m_name
     *
     * @param mName the value for mylike.m_name
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylike.username
     *
     * @return the value of mylike.username
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylike.username
     *
     * @param username the value for mylike.username
     *
     * @mbggenerated Wed Jul 06 13:45:59 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}